/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package net.aimeizi.person;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface PersonService {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"PersonService\",\"namespace\":\"net.aimeizi.person\",\"types\":[{\"type\":\"record\",\"name\":\"Person\",\"fields\":[{\"name\":\"age\",\"type\":\"int\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"sex\",\"type\":\"boolean\"},{\"name\":\"salary\",\"type\":\"double\"},{\"name\":\"childrenCount\",\"type\":\"int\"}]},{\"type\":\"record\",\"name\":\"QueryParameter\",\"fields\":[{\"name\":\"ageStart\",\"type\":\"int\"},{\"name\":\"ageEnd\",\"type\":\"int\"}]}],\"messages\":{\"ping\":{\"request\":[],\"response\":\"string\"},\"getPersonList\":{\"request\":[{\"name\":\"queryParameter\",\"type\":\"QueryParameter\"}],\"response\":{\"type\":\"array\",\"items\":\"Person\"}}}}");
  /**
   */
  java.lang.CharSequence ping() throws org.apache.avro.AvroRemoteException;
  /**
   */
  java.util.List<net.aimeizi.person.Person> getPersonList(net.aimeizi.person.QueryParameter queryParameter) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends PersonService {
    public static final org.apache.avro.Protocol PROTOCOL = net.aimeizi.person.PersonService.PROTOCOL;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void ping(org.apache.avro.ipc.Callback<java.lang.CharSequence> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void getPersonList(net.aimeizi.person.QueryParameter queryParameter, org.apache.avro.ipc.Callback<java.util.List<net.aimeizi.person.Person>> callback) throws java.io.IOException;
  }
}