/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package net.aimeizi.person;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class QueryParameter extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 9063777101000629314L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"QueryParameter\",\"namespace\":\"net.aimeizi.person\",\"fields\":[{\"name\":\"ageStart\",\"type\":\"int\"},{\"name\":\"ageEnd\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public int ageStart;
  @Deprecated public int ageEnd;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public QueryParameter() {}

  /**
   * All-args constructor.
   */
  public QueryParameter(java.lang.Integer ageStart, java.lang.Integer ageEnd) {
    this.ageStart = ageStart;
    this.ageEnd = ageEnd;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return ageStart;
    case 1: return ageEnd;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: ageStart = (java.lang.Integer)value$; break;
    case 1: ageEnd = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'ageStart' field.
   */
  public java.lang.Integer getAgeStart() {
    return ageStart;
  }

  /**
   * Sets the value of the 'ageStart' field.
   * @param value the value to set.
   */
  public void setAgeStart(java.lang.Integer value) {
    this.ageStart = value;
  }

  /**
   * Gets the value of the 'ageEnd' field.
   */
  public java.lang.Integer getAgeEnd() {
    return ageEnd;
  }

  /**
   * Sets the value of the 'ageEnd' field.
   * @param value the value to set.
   */
  public void setAgeEnd(java.lang.Integer value) {
    this.ageEnd = value;
  }

  /**
   * Creates a new QueryParameter RecordBuilder.
   * @return A new QueryParameter RecordBuilder
   */
  public static net.aimeizi.person.QueryParameter.Builder newBuilder() {
    return new net.aimeizi.person.QueryParameter.Builder();
  }
  
  /**
   * Creates a new QueryParameter RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new QueryParameter RecordBuilder
   */
  public static net.aimeizi.person.QueryParameter.Builder newBuilder(net.aimeizi.person.QueryParameter.Builder other) {
    return new net.aimeizi.person.QueryParameter.Builder(other);
  }
  
  /**
   * Creates a new QueryParameter RecordBuilder by copying an existing QueryParameter instance.
   * @param other The existing instance to copy.
   * @return A new QueryParameter RecordBuilder
   */
  public static net.aimeizi.person.QueryParameter.Builder newBuilder(net.aimeizi.person.QueryParameter other) {
    return new net.aimeizi.person.QueryParameter.Builder(other);
  }
  
  /**
   * RecordBuilder for QueryParameter instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<QueryParameter>
    implements org.apache.avro.data.RecordBuilder<QueryParameter> {

    private int ageStart;
    private int ageEnd;

    /** Creates a new Builder */
    private Builder() {
      super(net.aimeizi.person.QueryParameter.SCHEMA$);
    }
    
    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(net.aimeizi.person.QueryParameter.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.ageStart)) {
        this.ageStart = data().deepCopy(fields()[0].schema(), other.ageStart);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.ageEnd)) {
        this.ageEnd = data().deepCopy(fields()[1].schema(), other.ageEnd);
        fieldSetFlags()[1] = true;
      }
    }
    
    /**
     * Creates a Builder by copying an existing QueryParameter instance
     * @param other The existing instance to copy.
     */
    private Builder(net.aimeizi.person.QueryParameter other) {
            super(net.aimeizi.person.QueryParameter.SCHEMA$);
      if (isValidValue(fields()[0], other.ageStart)) {
        this.ageStart = data().deepCopy(fields()[0].schema(), other.ageStart);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.ageEnd)) {
        this.ageEnd = data().deepCopy(fields()[1].schema(), other.ageEnd);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'ageStart' field.
      * @return The value.
      */
    public java.lang.Integer getAgeStart() {
      return ageStart;
    }

    /**
      * Sets the value of the 'ageStart' field.
      * @param value The value of 'ageStart'.
      * @return This builder.
      */
    public net.aimeizi.person.QueryParameter.Builder setAgeStart(int value) {
      validate(fields()[0], value);
      this.ageStart = value;
      fieldSetFlags()[0] = true;
      return this; 
    }

    /**
      * Checks whether the 'ageStart' field has been set.
      * @return True if the 'ageStart' field has been set, false otherwise.
      */
    public boolean hasAgeStart() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'ageStart' field.
      * @return This builder.
      */
    public net.aimeizi.person.QueryParameter.Builder clearAgeStart() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'ageEnd' field.
      * @return The value.
      */
    public java.lang.Integer getAgeEnd() {
      return ageEnd;
    }

    /**
      * Sets the value of the 'ageEnd' field.
      * @param value The value of 'ageEnd'.
      * @return This builder.
      */
    public net.aimeizi.person.QueryParameter.Builder setAgeEnd(int value) {
      validate(fields()[1], value);
      this.ageEnd = value;
      fieldSetFlags()[1] = true;
      return this; 
    }

    /**
      * Checks whether the 'ageEnd' field has been set.
      * @return True if the 'ageEnd' field has been set, false otherwise.
      */
    public boolean hasAgeEnd() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'ageEnd' field.
      * @return This builder.
      */
    public net.aimeizi.person.QueryParameter.Builder clearAgeEnd() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public QueryParameter build() {
      try {
        QueryParameter record = new QueryParameter();
        record.ageStart = fieldSetFlags()[0] ? this.ageStart : (java.lang.Integer) defaultValue(fields()[0]);
        record.ageEnd = fieldSetFlags()[1] ? this.ageEnd : (java.lang.Integer) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);  

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, org.apache.avro.specific.SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);  

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, org.apache.avro.specific.SpecificData.getDecoder(in));
  }

}
